#!/usr/bin/env python3
"""Build Zero's per-frame saber collision masks from MMX-Next sprites.

GameMaker uses collisionKind=4 (precise, per-frame) for these sprites.  Instead
of replacing that with one oversized rectangle, this converts every opaque row
run into merged Rect2 cells.  The generated Godot data therefore follows the
actual blade artwork and the same 60 Hz animation timeline as MMX-Next.
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from gml_rip import Sprite


# Target ability attack -> (MMX-Next animation, precise collision sprite).
# Ryuenjin and Raikousen deliberately use their dedicated GameMaker masks, just
# as player_saber_after_step.gml does; the other attacks collide on saber art.
ATTACKS = {
    "atk1": ("atk_1", "spr_zero_saber_1"),
    "atk2": ("atk_2", "spr_zero_saber_2"),
    "atk3": ("atk_3", "spr_zero_saber_3"),
    "jump": ("atk_jump", "spr_zero_saber_jump"),
    "wall": ("atk_wall", "spr_zero_saber_wall"),
    "mikazukizan": ("atk_mikazukizan", "spr_zero_saber_mikazukizan"),
    "ryuenjin": ("atk_ryuenjin", "spr_zero_saber_ryuenjin_mask"),
    "hyouretsuzan": ("atk_hyouretsuzan", "spr_zero_saber_hyouretsuzan"),
    "shippuuga": ("atk_shippuuga", "spr_zero_saber_shippuuga"),
    "raikousen": ("atk_raikousen", "spr_zero_saber_raikousen_mask"),
}


def opaque_rects(image, origin):
    """Losslessly merge identical horizontal alpha runs across adjacent rows."""
    alpha = image.getchannel("A")
    pixels = alpha.load()
    width, height = image.size
    open_rects = {}
    complete = []

    for y in range(height):
        spans = []
        x = 0
        while x < width:
            while x < width and pixels[x, y] == 0:
                x += 1
            start = x
            while x < width and pixels[x, y] != 0:
                x += 1
            if start < x:
                spans.append((start, x))

        next_open = {}
        for span in spans:
            if span in open_rects:
                rect = open_rects[span]
                rect[3] += 1
            else:
                rect = [span[0] - origin[0], y - origin[1], span[1] - span[0], 1]
            next_open[span] = rect

        for span, rect in open_rects.items():
            if span not in next_open:
                complete.append(rect)
        open_rects = next_open

    complete.extend(open_rects.values())
    return sorted(complete, key=lambda r: (r[1], r[0], r[2], r[3]))


def gd_rect(rect):
    return "Rect2( %d, %d, %d, %d )" % tuple(rect)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--sprites-dir", required=True)
    parser.add_argument("--anims", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    animations = json.load(open(args.anims))
    built = {}
    total_rects = 0

    for attack, (animation_name, sprite_name) in ATTACKS.items():
        animation = animations.get(animation_name)
        if animation is None:
            parser.error("animation not found: %s" % animation_name)

        sprite = Sprite(args.sprites_dir, sprite_name)
        masks = [opaque_rects(image, sprite.origin) for image in sprite.images]
        timeline = animation["frames"]
        if timeline and max(timeline) >= len(masks):
            parser.error("%s uses frame %d but %s has only %d frames"
                         % (animation_name, max(timeline), sprite_name, len(masks)))

        built[attack] = {
            "timeline": timeline,
            "loop": animation["loop"],
            "masks": masks,
        }
        total_rects += sum(len(frame) for frame in masks)

    lines = [
        "# Generated by tools/build_zero_saber_masks.py from MMX-Next.",
        "# Do not hand-edit; rerun tools/rip_zero.sh.",
        "extends Reference",
        "",
        "const DATA := {",
    ]
    for attack, data in built.items():
        lines.append('\t"%s": {' % attack)
        lines.append('\t\t"timeline": [ %s ],' % ", ".join(map(str, data["timeline"])))
        lines.append('\t\t"loop": [ %s ],' % ", ".join(map(str, data["loop"])))
        lines.append('\t\t"masks": [')
        for frame in data["masks"]:
            lines.append("\t\t\t[ %s ]," % ", ".join(gd_rect(rect) for rect in frame))
        lines.append("\t\t],")
        lines.append("\t},")
    lines.extend([
        "}",
        "",
        "static func rects_for(attack : String, step : int) -> Array:",
        "\tvar data : Dictionary = DATA.get(attack, {})",
        "\tif data.empty() or data.timeline.empty():",
        "\t\treturn []",
        "\tvar timeline_step := step",
        "\tif timeline_step >= data.timeline.size():",
        "\t\tif data.loop.size() != 2:",
        "\t\t\ttimeline_step = data.timeline.size() - 1",
        "\t\telse:",
        "\t\t\tvar loop_start : int = data.loop[0]",
        "\t\t\tvar loop_end : int = min(data.loop[1], data.timeline.size() - 1)",
        "\t\t\tvar loop_length : int = max(1, loop_end - loop_start + 1)",
        "\t\t\ttimeline_step = loop_start + ((timeline_step - data.timeline.size()) % loop_length)",
        "\tvar mask_index : int = data.timeline[max(0, timeline_step)]",
        "\treturn data.masks[mask_index]",
        "",
    ])

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as output:
        output.write("\n".join(lines))
    print("wrote %s: %d attacks, %d merged mask cells"
          % (args.out, len(built), total_rects))


if __name__ == "__main__":
    main()
